### ISSUE TITLE
Update the visibility of the response attribute of exceptions

### ISSUE THREAD

**Issue by sharovik** [CoverGenius/xcover-php#2]
As you can see in the link below, the response attribute can be used only inside of exception, which is not really useful, once you want to log more details about the response of the API. Of course, some of the response items cannot be exposed in the logs for security reasons... But anyway, at least this can give more context about the error.

I would propose to change the visibility of the `getFromResponse` method to `public`, so everybody outside of the exception class can use it.

What do you think?
https://github.com/CoverGenius/xcover-php/blob/42d780702dc685ec1b982175d6991431cdc4a66d/src/Exceptions/ResponseException.php#L42

**Comment by tyomo4ka** [comment]
Hey @sharovik. That's a good suggestion. I didn't think about this use case. But it makes a lot of sense. I will add this change straight away.

**Comment by tyomo4ka** [comment]
@sharovik 

I just released the change you requested as v.1.0.3. 

I added a getter for `response` object on the ResponseException class and also increased the visibility of  `getFromResponse` method to protected. It's not exactly what you proposed, but hopefully will make your life easier when you develop and debug your code.

**Comment by sharovik** [comment]
Thanks!
